import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar/NavBar";
import Footer from "@/components/footer/Footer";
import { ThemeProvider, ThmeneProvider } from "@/context/ThemeContext";
import AuthProvired from "@/components/provider/AuthProvired";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DegitalNexusWork",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
        <AuthProvired>
          <div className="container">
            <NavBar></NavBar>
            {children}
            <Footer></Footer>
          </div>
          </AuthProvired>
        </ThemeProvider>
      </body>
    </html>
  );
}
